name: ecshop_techpit
description: Sample Application for Techpit

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_riverpod: ^2.0.0-dev.9
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  go_router: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/mock.json
